# Generated by Django 5.1.5 on 2025-04-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path_type', models.CharField(choices=[('SO', 'Soft'), ('GR', 'Gravel'), ('DT', 'Dirt'), ('HD', 'Hard'), ('PV', 'Paved'), ('CO', 'Concrete')], default='SOFT', max_length=2)),
                ('terrain_type', models.CharField(choices=[('FL', 'Flat'), ('HL', 'Hilly'), ('UN', 'Uneven')], default='FLAT', max_length=2)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('running_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_places.runningplace')),
            ],
        ),
    ]
