# Generated by Django 5.1.5 on 2025-04-27 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path_type', models.CharField(choices=[('GR', 'Gravel'), ('DT', 'Dirt'), ('PV', 'Paved'), ('CO', 'Concrete')], default='Gravel', max_length=2)),
                ('terrain_type', models.CharField(choices=[('FL', 'Flat'), ('HL', 'Hilly')], default='Flat', max_length=2)),
                ('length', models.IntegerField()),
                ('parking', models.CharField(choices=[('FR', 'Free'), ('PA', 'Paid')], default='Free', max_length=2)),
                ('restroom', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=2)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('running_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_places.runningplace')),
            ],
        ),
    ]
