# Generated by Django 5.1.5 on 2025-04-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='RunningPlace',
            name='location',
            field=models.CharField(default='TBD', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='RunningPlace',
            name='name',
            field=models.CharField(default='Unnamed Place', max_length=100),
            preserve_default=False,
        ),
    ]
