# Generated by Django 5.1.5 on 2025-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningplace',
            name='parking',
            field=models.CharField(choices=[('FR', 'Free'), ('PA', 'Paid')], default='Paid', max_length=2),
        ),
        migrations.AddField(
            model_name='runningplace',
            name='restroom',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='runningplace',
            name='path_type',
            field=models.CharField(choices=[('GR', 'Gravel'), ('DT', 'Dirt'), ('PV', 'Paved'), ('CO', 'Concrete')], default='Gravel', max_length=2),
        ),
        migrations.AlterField(
            model_name='runningplace',
            name='terrain_type',
            field=models.CharField(choices=[('FL', 'Flat'), ('HL', 'Hilly')], default='Flat', max_length=2),
        ),
    ]
