# Generated by Django 5.1.7 on 2025-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_place',
            name='path_type',
            field=models.CharField(choices=[('SO', 'Soft'), ('GR', 'Gravel'), ('DT', 'Dirt'), ('HD', 'Hard'), ('PV', 'Paved'), ('CR', 'Concrete')], default='SO', max_length=2),
        ),
    ]
