# Generated by Django 5.1.7 on 2025-04-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_places', '0002_running_place_path_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_place',
            name='terrain_type',
            field=models.CharField(choices=[('FL', 'Flat'), ('HL', 'Hilly'), ('UN', 'Uneven')], default='FL', max_length=2),
        ),
    ]
