# Generated by Django 5.1.7 on 2025-04-01 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_places', '0003_running_place_terrain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_place',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
